/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CarrinhoDao;
import dao.ConfirmacaoDao;
import dao.ConnectionFactory;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.Carrinho;
import model.Confirmacao;
import table.CarrinhoTableModel;
import static view.Login.codigo_pessoa;
import static view.Login.getCodigo_pessoa;

/**
 *
 * @author Dário Felipe
 */
public class TelaCarrinho extends javax.swing.JFrame {
    
    public static int codigo_carrinho;

    public static int getCodigo_carrinho() {
        return codigo_carrinho;
    }

    public static void setCodigo_carrinho(int codigo_carrinho) {
        TelaCarrinho.codigo_carrinho = codigo_carrinho;
    }
    
    int codigo = getCodigo_pessoa();
   
    Confirmacao cof = new Confirmacao();
    ConfirmacaoDao cod = new ConfirmacaoDao();
    
    Carrinho car = new Carrinho();
    CarrinhoDao cad = new CarrinhoDao();
    
    private Connection cf1;
    private PreparedStatement stmt1;
    private Statement st1;
    private ResultSet rs1;
    
    
    public boolean PegarCodCar(){           
        
    try{
            cf1 = new ConnectionFactory().getConexao();                   
            String sql = "SELECT codigo_carrinho FROM carrinho'";
        
            stmt1 = cf1.prepareStatement(sql); 
            rs1 = stmt1.executeQuery();
            
                rs1.first();
                codigo_carrinho = rs1.getInt("codigo_carrinho");
                   
       }catch(SQLException e){
           return false;
       } 
       return false;
     }
    
    /**
     * Creates new form TelaCarrinho
     */
    
    public TelaCarrinho() {
        initComponents();
        this.setLocationRelativeTo(null);
        tfcodigo.setVisible(false);
        tfcodigoconfirmacao.setVisible(false);
        tbcarrinho.setModel(new CarrinhoTableModel(new CarrinhoDao().Listartodos(codigo)));
        setIcon();
        
        PegarCodCar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbcarrinho = new javax.swing.JTable();
        lblVoltar = new javax.swing.JLabel();
        btexcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tfcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoconfirmacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CYBER CARRINHO");
        setResizable(false);

        tbcarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbcarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcarrinhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcarrinho);

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Setas.png"))); // NOI18N
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        btexcluir.setText("Retirar");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        jButton1.setText("Frete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfcodigo.setEditable(false);
        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CarrinhoGigante.png"))); // NOI18N
        jLabel1.setText("<html><hr>CYBER TECNOLOGY<hr></html>");

        tfcodigoconfirmacao.setEditable(false);
        tfcodigoconfirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoconfirmacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVoltar)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfcodigoconfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btexcluir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVoltar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcodigoconfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btexcluir)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbcarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcarrinhoMouseClicked
      
        tfcodigo.setText(tbcarrinho.getValueAt(tbcarrinho.getSelectedRow(), CarrinhoTableModel.COL_CODIGO_CARRINHO).toString());
    }//GEN-LAST:event_tbcarrinhoMouseClicked

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:

        dispose();
        new InterfaceInicial().setVisible(true);
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here:
        int codigo2 = Integer.parseInt(tfcodigo.getText());
        cad.excluir(codigo2);
        cod.excluir(Integer.parseInt(tfcodigo.getText()));
        tfcodigo.setText("");
        tbcarrinho.setModel(new CarrinhoTableModel(new CarrinhoDao().Listartodos(codigo)));
        
    }//GEN-LAST:event_btexcluirActionPerformed

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tbcarrinho.getRowCount()==0){
            
            JOptionPane.showMessageDialog(null, "Sem produtos, adicione produtos ao carrinho!");
        } else{
            
            dispose(); 
            new TelaFrete().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfcodigoconfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoconfirmacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoconfirmacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTable tbcarrinho;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfcodigoconfirmacao;
    // End of variables declaration//GEN-END:variables

     private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LogoMenor.png")));
    }

}
